### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by yazhinia** [BGU-CS-VIL/pdc-dp-means#7]
Hi,
I couldn't install due to following error.

pip install pdc-dp-means
ERROR: Could not find a version that satisfies the requirement pdc-dp-means (from versions: none)
ERROR: No matching distribution found for pdc-dp-means

Any input is much appreciated.

**Comment by dinarior** [comment]
Hi,

Which Python version, and which OS are you using?

**Comment by yazhinia** [comment]
Python version: 3.12.3
OS: Ubuntu 24.04 LTS

**Comment by dinarior** [comment]
There are no pre-compiled binaries for python 3.12, please check if 3.11 works for you.

I will try to add them, but it might take some time before I get to it.

**Comment by yazhinia** [comment]
Yes, with lower version it works. Thank you for prompt reply.
I would like to apply this method for millions of data points with thousands of clusters. Could you give insights on the feasibility?

Thank you.

**Comment by dinarior** [comment]
Hi,
Yes it should work, You should use the MiniBatch version however, as the vanilla version takes time for initializing alot of clusters (you can also use the Vanilla version with DACE, see the paper, and theres a pure python example in the "paper code" directory). 

The MiniBatch however should do the trick.

Also, I have uploaded wheels for python 3.12, so should be fine now.
